import Head from "next/head";
import { Pagination, Table } from "react-bootstrap";
import { Container } from "react-bootstrap";
import { NavBar } from "../components/navbar";
import { Footer } from "../components/footer";
import { AuthenticateEmployee } from "../helpers/AuthenticateEmployee";
import { LogsQueries } from "../queries/logs";
import { useEffect, useState } from "react";

export default function activitylogs({ token, _logs, employee }) {
  const [logs, setLogs] = useState(_logs);
  const [pageCount] = useState(_logs.totalCount % 10);
  const [currentPageNumber, setCurrentPageNumber] = useState(1);

  return (
    <>
      <>
        <Head>
          <title>Vaperous M4ster - POS Website</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/img/Logo.jpg" />
        </Head>
        <NavBar employee={employee}></NavBar>
        <div>
          <h1 className="fs-2 text-center"> Activity Logs </h1>
        </div>
        <div>
          <h3 className="text-center py-3">Vaperous Master's Activity Logs</h3>
        </div>

        <Container class="d-flex align-items-center flex-column mx-md-5">
          <Table striped bordered hover variant="dark">
            <thead>
              <tr>
                <th>ID</th>
                <th>DATE CREATED</th>
                <th>CREATED BY</th>
                <th>DESCRIPTION</th>
              </tr>
            </thead>
            <tbody>
              {logs.edges.map((edge, key) => (
                <tr key={key}>
                  <td>{edge.node.id}</td>
                  <td>{new Date(edge.node.createdAt).toLocaleString()}</td>
                  <td>
                    {edge.node.employee.firstName} {edge.node.employee.lastName}
                  </td>
                  <td>{edge.node.description}</td>
                </tr>
              ))}
            </tbody>
          </Table>
          <Pagination>
            <Pagination.Prev
              onClick={() => {
                if (currentPageNumber == 1 && !logs.pageInfo.hasPreviousPage) return;

                LogsQueries.getAllPaginate(token, 10, {
                  before: logs.pageInfo.startCursor,
                })
                  .then((res) => {
                    setLogs(res.data.logs);
                    setCurrentPageNumber(currentPageNumber - 1);
                  })
                  .catch((err) => console.log(err.response));

              }}
            />
            {Array.from(Array(pageCount)).map((_, key) => (
              <Pagination.Item
                key={key}
                active={
                  Number.parseInt(currentPageNumber) == Number.parseInt(key + 1)
                }
              >
                {key + 1}
              </Pagination.Item>
            ))}
            <Pagination.Next
              onClick={() => {
                if (currentPageNumber == pageCount && !logs.pageInfo.hasNextPage) return;

                LogsQueries.getAllPaginate(token, 10, {
                  after: logs.pageInfo.endCursor,
                })
                  .then((res) => {
                    setLogs(res.data.logs);
                    setCurrentPageNumber(currentPageNumber + 1);
                  })
                  .catch((err) => console.log(err.response));
              }}
            />
          </Pagination>
        </Container>
      </>
      <Footer></Footer>
    </>
  );
}

export async function getServerSideProps(context) {
  const employee = await AuthenticateEmployee(context);

  if (employee.props.token) {
    const data = (await LogsQueries.getAllPaginate(employee.props.token, 10))
      .data;

    return {
      props: {
        ...employee.props,
        _logs: data.logs,
      },
    };
  }

  return {
    props: {
      ...employee.props,
    },
  };
}
