import Head from 'next/head'
import {Card} from "react-bootstrap"
import { NavBar } from '../components/navbar'
import { Footer } from '../components/footer'
import { AuthenticateEmployee } from '../helpers/AuthenticateEmployee'


export default function Employee({employee}) {
  return (
    <div>
      <Head>
        <title>Vaperous M4ster - POS Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/Logo.jpg" />
      </Head>
    <NavBar employee={employee}></NavBar>
    <br></br>
    <div> 
        <h1 className="fs-2 text-center"> Employee</h1>
        </div>
    
      <div className="container justify-content-center text-center">
        <div className="row py-3">
        <div className="col-md-3">
          <a className="text-decoration-none text-black" href="">
          <Card className="shadow-lg rounded " style={{ width: '16rem' }}>
          <Card.Img variant="top" src="/img/ " />
          <Card.Body>
            <Card.Title>Hala Man</Card.Title>
          </Card.Body>
          </Card>
          </a>
        </div>




        <div className="col-md-3">
          <a className="text-decoration-none text-black" href="">
          <Card className="shadow-lg rounded " style={{ width: '16rem' }}>
          <Card.Img variant="top" src="/img/ " />
          <Card.Body>
            <Card.Title>Sige Talon</Card.Title>
          </Card.Body>
          </Card>
          </a>
        </div>


        <div className="col-md-3">
          <a className="text-decoration-none text-black" href="">
          <Card className="shadow-lg rounded " style={{ width: '16rem' }}>
          <Card.Img variant="top" src="/img/ " />
          <Card.Body>
            <Card.Title>Ha Duken</Card.Title>
          </Card.Body>
          </Card>
          </a>
        </div>


        <div className="col-md-3">
          <a className="text-decoration-none text-black" href="">
          <Card className="shadow-lg rounded " style={{ width: '16rem' }}>
          <Card.Img variant="top" src="/img/ " />
          <Card.Body>
            <Card.Title>Ako Lang</Card.Title>
          </Card.Body>
          </Card>
          </a>
        </div>


        <div className="col-md-3">
          <a className="text-decoration-none text-black" href="">
          <Card className="shadow-lg rounded " style={{ width: '16rem' }}>
          <Card.Img variant="top" src="/img/ " />
          <Card.Body>
            <Card.Title>Ewan Ko</Card.Title>
          </Card.Body>
          </Card>
          </a>
        </div>


        <div className="col-md-3">
          <a className="text-decoration-none text-black" href="">
          <Card className="shadow-lg rounded " style={{ width: '16rem' }}>
          <Card.Img variant="top" src="/img/ " />
          <Card.Body>
            <Card.Title>Bahag Hari</Card.Title>
          </Card.Body>
          </Card>
          </a>
        </div>



        <div className="col-md-3">
          <a className="text-decoration-none text-black" href="">
          <Card className="shadow-lg rounded " style={{ width: '16rem' }}>
          <Card.Img variant="top" src="/img/ " />
          <Card.Body>
            <Card.Title>Hay Buhay</Card.Title>
          </Card.Body>
          </Card>
          </a>
        </div>
        </div>
      </div>
     

    <Footer></Footer>
    </div>
  )
}
export async function getServerSideProps(context) {
  return AuthenticateEmployee(context);
}