import Head from 'next/head'
import { Container, Row, Col, Card, Table, InputGroup, Button, Form, FormControl } from "react-bootstrap"
import Deleteemp from '../components/deleteemp'
import Editemp from '../components/editemp'
import Addemp from '../components/addemp'
import { useEffect, useState } from 'react'
import { NavBar } from '../components/navbar'
import {AiFillEdit} from "react-icons/ai"
import { Footer } from '../components/footer'
import { AuthenticateEmployee } from '../helpers/AuthenticateEmployee'
import axios from 'axios'
import { BACKEND } from '../helpers'


export default function Empadsee({employee,allEmployees, token}) {
  const [modalShow, setModalShow] = useState(false, true);
  
  return (
    <div>
      <Head>
        <title>Vaperous M4ster - POS Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/Logo.jpg" />
      </Head>
    <NavBar employee={employee}></NavBar>
    <br></br>
    <div class=" d-flex mt-3 justify-content-center" style={{ width: "100%"}}>
      
        <label className="mb-2"
          style={{
            fontSize: "2em",
            fontWeight: "bold",
            fontFamily: 'Roboto',

          }}
        >
          EMPLOYEE{" "}
        </label>
      </div>
    <Container className="col-lg-12 my-3 rounded-3">  
    <Row>
    <Col className='p-2'>
      <div className="text-end">
    <Addemp token={token}></Addemp>
      </div>
    </Col>
  </Row>
    

  <Table striped bordered hover className="table table-image" >
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Image</th>
      <th scope="col">First Name</th>
      <th scope="col">LastName</th>
      <th scope="col">Role</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    { allEmployees && allEmployees.map ((employee) => (
          <tr>
          <th scope="row">{employee.id}</th>
          <td className="w-25">
          {employee.images && employee.images.length > 0 && <img src={BACKEND + employee.images[0].location}  className="img-fluid img-employee" alt="employ"/>}</td>
          <td>{employee.firstName}</td>
          <td>{employee.lastName}</td>
          <td>{employee.type}</td>
          <td class="py-2">
             <Editemp></Editemp>
              <Deleteemp></Deleteemp>
          </td>
        </tr>
    ))}
  </tbody>
</Table>

</Container>   
    <Footer></Footer>
  
    </div>
  )
}
export async function getServerSideProps(context) {
  const allEmployees=await axios.get(BACKEND + "/api/employees/all")
 const employee = await AuthenticateEmployee(context)

 if (employee.props.employee.type == "CASHIER"){ 
   return {
     redirect: {
       destination: "/employee",
       permanent: false,
     },
     props: {},
   };
 }
 return{
   props: {
     allEmployees:allEmployees.data.employees,
     ...(employee).props
   }

 }
}
