import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { NavBar } from '../components/navbar'
import { Footer } from '../components/footer'
import { useEffect, useState } from 'react'

export default function Home() {
  const [counter,setCounter]=useState(0)
  useEffect(()=>{
    setCounter (5)
  },[])
  return (
    <div>
      <Head>
        <title>Vaperous M4ster - POS Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/Logo.jpg" />
      </Head>
    <NavBar></NavBar>

    
      
      <div className="container">
      <button onClick={()=>setCounter(counter+1)} className="btn btn-primary btn-lg">{counter}</button>
      <div className="row">


      <div> 
        <h1 className="fs-5 text-end"> Hello Aczell</h1>
        </div>

        <div className="col-md-3">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nulla turpis, elementum sed risus id, eleifend porta ligula. Maecenas commodo lorem quis dictum vehicula. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eros ante, porttitor non purus vitae, varius dictum dolor. Cras gravida felis non dui cursus tincidunt. Cras nec libero sem. Fusce eget lectus sed nibh tristique facilisis a eget dolor. Vivamus blandit iaculis ex, vel semper neque pharetra porta. Aliquam congue diam id leo cursus, sit amet egestas urna vulputate. Curabitur nec lorem eget nisl condimentum iaculis quis eu dolor. Mauris vitae sem quam. Quisque hendrerit sodales felis ut dictum. Etiam ullamcorper vestibulum quam a auctor.</p>
      </div>



      <div className="col-md-3">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nulla turpis, elementum sed risus id, eleifend porta ligula. Maecenas commodo lorem quis dictum vehicula. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eros ante, porttitor non purus vitae, varius dictum dolor. Cras gravida felis non dui cursus tincidunt. Cras nec libero sem. Fusce eget lectus sed nibh tristique facilisis a eget dolor. Vivamus blandit iaculis ex, vel semper neque pharetra porta. Aliquam congue diam id leo cursus, sit amet egestas urna vulputate. Curabitur nec lorem eget nisl condimentum iaculis quis eu dolor. Mauris vitae sem quam. Quisque hendrerit sodales felis ut dictum. Etiam ullamcorper vestibulum quam a auctor.</p>
      </div>

      
      <div className="col-md-3">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nulla turpis, elementum sed risus id, eleifend porta ligula. Maecenas commodo lorem quis dictum vehicula. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eros ante, porttitor non purus vitae, varius dictum dolor. Cras gravida felis non dui cursus tincidunt. Cras nec libero sem. Fusce eget lectus sed nibh tristique facilisis a eget dolor. Vivamus blandit iaculis ex, vel semper neque pharetra porta. Aliquam congue diam id leo cursus, sit amet egestas urna vulputate. Curabitur nec lorem eget nisl condimentum iaculis quis eu dolor. Mauris vitae sem quam. Quisque hendrerit sodales felis ut dictum. Etiam ullamcorper vestibulum quam a auctor.</p>
      </div>

      <div className="col-md-3">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nulla turpis, elementum sed risus id, eleifend porta ligula. Maecenas commodo lorem quis dictum vehicula. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eros ante, porttitor non purus vitae, varius dictum dolor. Cras gravida felis non dui cursus tincidunt. Cras nec libero sem. Fusce eget lectus sed nibh tristique facilisis a eget dolor. Vivamus blandit iaculis ex, vel semper neque pharetra porta. Aliquam congue diam id leo cursus, sit amet egestas urna vulputate. Curabitur nec lorem eget nisl condimentum iaculis quis eu dolor. Mauris vitae sem quam. Quisque hendrerit sodales felis ut dictum. Etiam ullamcorper vestibulum quam a auctor.</p>
      </div>

      </div>
      </div>

    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nulla turpis, elementum sed risus id, eleifend porta ligula. Maecenas commodo lorem quis dictum vehicula. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eros ante, porttitor non purus vitae, varius dictum dolor. Cras gravida felis non dui cursus tincidunt. Cras nec libero sem. Fusce eget lectus sed nibh tristique facilisis a eget dolor. Vivamus blandit iaculis ex, vel semper neque pharetra porta. Aliquam congue diam id leo cursus, sit amet egestas urna vulputate. Curabitur nec lorem eget nisl condimentum iaculis quis eu dolor. Mauris vitae sem quam. Quisque hendrerit sodales felis ut dictum. Etiam ullamcorper vestibulum quam a auctor.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nulla turpis, elementum sed risus id, eleifend porta ligula. Maecenas commodo lorem quis dictum vehicula. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eros ante, porttitor non purus vitae, varius dictum dolor. Cras gravida felis non dui cursus tincidunt. Cras nec libero sem. Fusce eget lectus sed nibh tristique facilisis a eget dolor. Vivamus blandit iaculis ex, vel semper neque pharetra porta. Aliquam congue diam id leo cursus, sit amet egestas urna vulputate. Curabitur nec lorem eget nisl condimentum iaculis quis eu dolor. Mauris vitae sem quam. Quisque hendrerit sodales felis ut dictum. Etiam ullamcorper vestibulum quam a auctor.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nulla turpis, elementum sed risus id, eleifend porta ligula. Maecenas commodo lorem quis dictum vehicula. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eros ante, porttitor non purus vitae, varius dictum dolor. Cras gravida felis non dui cursus tincidunt. Cras nec libero sem. Fusce eget lectus sed nibh tristique facilisis a eget dolor. Vivamus blandit iaculis ex, vel semper neque pharetra porta. Aliquam congue diam id leo cursus, sit amet egestas urna vulputate. Curabitur nec lorem eget nisl condimentum iaculis quis eu dolor. Mauris vitae sem quam. Quisque hendrerit sodales felis ut dictum. Etiam ullamcorper vestibulum quam a auctor.</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nulla turpis, elementum sed risus id, eleifend porta ligula. Maecenas commodo lorem quis dictum vehicula. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eros ante, porttitor non purus vitae, varius dictum dolor. Cras gravida felis non dui cursus tincidunt. Cras nec libero sem. Fusce eget lectus sed nibh tristique facilisis a eget dolor. Vivamus blandit iaculis ex, vel semper neque pharetra porta. Aliquam congue diam id leo cursus, sit amet egestas urna vulputate. Curabitur nec lorem eget nisl condimentum iaculis quis eu dolor. Mauris vitae sem quam. Quisque hendrerit sodales felis ut dictum. Etiam ullamcorper vestibulum quam a auctor.</p>
    <Footer></Footer>

   
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
  <script>
    AOS.init();
  </script>

    </div>
  )
}
