import Head from "next/head";
import {
  Container,
  Row,
  Col,
  Card,
  Table,
  InputGroup,
  Button,
  Form,
  FormControl,
  ButtonGroup,
} from "react-bootstrap";
import Image from "next/image";
import {
  FaPlusCircle,
  FaMinusCircle,
  FaTrashAlt,
  FaShoppingCart,
  FaSearch,
  FaBarcode,
} from "react-icons/fa";
import styles from "../styles/Home.module.css";
import { NavBar } from "../components/navbar";
import { Footer } from "../components/footer";
import { useEffect, useState } from "react";
import { CheckoutModal } from "../components/home/checkout";
import { AuthenticateEmployee } from "../helpers/AuthenticateEmployee";
import { CategoriesQueries } from "../queries/categories";
import { ProductsQueries } from "../queries/products";
import { VariantsQueries } from "../queries/variants";
import { POSCategoryViewer } from "../components/pos/CategoryViewer";
import { POSCartViewer } from "../components/pos/CartViewer";

export default function Home({ employee, categories, token }) {
  const [modalShow, setModalShow] = useState(false);
  const [activeCategoryKey, setActiveCategoryKey] = useState(0);
  const [cartItems, setCartItems] = useState([]);

  return (
    <div>
      <Head>
        <title>Vaperous M4ster - POS Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/Logo.jpg" />
      </Head>
      <NavBar employee={employee}></NavBar>

      <Container fluid>
        <Row className="p-5">
          <Col xs={{ order: 2 }} md={{ span: 9, order: 1 }}>
            {/* Column for product view */}
            <ButtonGroup aria-label="Categories" className="w-100">
              {categories.map((category, key) => (
                <Button
                  variant={key == activeCategoryKey ? "primary" : "secondary"}
                  onClick={() => setActiveCategoryKey(key)}
                >
                  {category.name}
                </Button>
              ))}
            </ButtonGroup>
            <POSCategoryViewer
              setCartItems={setCartItems}
              category={categories[activeCategoryKey]}
              token={token}
            />
          </Col>
          <Col
            xs={{ order: 1 }}
            md={{ span: 3, order: 2 }}
            className="position-relative"
          >
            <POSCartViewer cartItems={cartItems} setCartItems={setCartItems} />
          </Col>
        </Row>
      </Container>

      <CheckoutModal show={modalShow} onHide={() => setModalShow(false)} />

      <Footer></Footer>
    </div>
  );
}
export async function getServerSideProps(context) {
  const { props } = await AuthenticateEmployee(context);

  if (!props.employee) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }
  //Get all categories
  let categories = (await CategoriesQueries.getAll(props.token)).data
    .categories;

  return {
    props: {
      ...props,
      categories,
    },
  };
}
