import Head from 'next/head'
import {Card} from "react-bootstrap"
import styles from '../styles/inventory.module.css'
import { NavBar } from '../components/navbar'
import { Footer } from '../components/footer'



export default function Inventory() {
  return (
    <div>
      <Head>
        <title>Vaperous M4ster - POS Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/Logo.jpg" />
      </Head>
    <NavBar></NavBar>
    
      <h1 className="text-center">Heading </h1>
      <div className="container col-lg-10 justify-content-center ">
        <div className="row">
        
        <div className="col-md-3 py-3">
        <a className="text-decoration-none text-black" href="">
        <Card  data-aos="fade-down" className="shadow-lg rounded-3" border="light" variant="transparent" style={{ width: '15rem' }}>
          <Card.Img   variant="top" src="/img/93f895b604a807de99d813ec8a2e53db.jpg" />
          <Card.Text className="text-center p-2">
            JUICES
          </Card.Text>
        </Card>
      </a>
    </div>


    <div className="col-md-3 py-3">
        <a className="text-decoration-none text-black" href="">
        <Card className="shadow-lg rounded-3" border="light" variant="transparent" style={{ width: '15rem' }}>
          <Card.Img   variant="top" src="/img/93f895b604a807de99d813ec8a2e53db.jpg" />
          <Card.Text className="text-center p-2">
            JUICES
          </Card.Text>
        </Card>
      </a>
    </div>


    <div className="col-md-3 py-3">
        <a className="text-decoration-none text-black" href="">
        <Card className="shadow-lg rounded-3" border="light" variant="transparent" style={{ width: '15rem' }}>
          <Card.Img   variant="top" src="/img/93f895b604a807de99d813ec8a2e53db.jpg" />
          <Card.Text className="text-center p-2">
            JUICES
          </Card.Text>
        </Card>
      </a>
    </div>


    <div className="col-md-3 py-3">
        <a className="text-decoration-none text-black" href="">
        <Card className="shadow-lg rounded-3" border="light" variant="transparent" style={{ width: '15rem' }}>
          <Card.Img   variant="top" src="/img/93f895b604a807de99d813ec8a2e53db.jpg" />
          <Card.Text className="text-center p-2">
            JUICES
          </Card.Text>
        </Card>
      </a>
    </div>

    <div className="col-md-3 py-2">
        <a className="text-decoration-none text-black" href="">
        <Card className="shadow-lg rounded-3" border="light" variant="transparent" style={{ width: '15rem' }}>
          <Card.Img   variant="top" src="/img/93f895b604a807de99d813ec8a2e53db.jpg" />
          <Card.Text className="text-center p-2">
            JUICES
          </Card.Text>
        </Card>
      </a>
    </div>

    <div className="col-md-3 py-2">
        <a className="text-decoration-none text-black" href="">
        <Card className="shadow-lg rounded-3" border="light" variant="transparent" style={{ width: '15rem' }}>
          <Card.Img   variant="top" src="/img/93f895b604a807de99d813ec8a2e53db.jpg" />
          <Card.Text className="text-center p-2">
            JUICES
          </Card.Text>
        </Card>
      </a>
    </div>

    <div className="col-md-3 py-2">
        <a className="text-decoration-none text-black" href="">
        <Card className="shadow-lg rounded-3" border="light" variant="transparent" style={{ width: '15rem' }}>
          <Card.Img   variant="top" src="/img/93f895b604a807de99d813ec8a2e53db.jpg" />
          <Card.Text className="text-center p-2">
            JUICES
          </Card.Text>
        </Card>
      </a>
    </div>

    <div className="col-md-3 py-2">
        <a className="text-decoration-none text-black" href="">
        <Card className="shadow-lg rounded-3" border="light" variant="transparent" style={{ width: '15rem' }}>
          <Card.Img   variant="top" src="/img/93f895b604a807de99d813ec8a2e53db.jpg" />
          <Card.Text className="text-center p-2">
            JUICES
          </Card.Text>
        </Card>
      </a>
    </div>



        </div>
      </div>


    <Footer></Footer>
    </div>
  )
}
