<<<<<<< Updated upstream
import Head from 'next/head'
import {Card} from "react-bootstrap"
import styles from '../styles/inventory.module.css'
import { NavBar } from '../components/navbar'
import { Footer } from '../components/footer'
import { AuthenticateEmployee } from '../helpers/AuthenticateEmployee'



export default function Inventory({employee}) {
=======
import Head from "next/head";
import { Card, Button } from "react-bootstrap";
import styles from "../styles/inventory.module.css";
import { NavBar } from "../components/navbar";
import { Footer } from "../components/footer";
import { AuthenticateEmployee } from "../helpers/AuthenticateEmployee";
import { CategoriesQueries } from "../queries/categories";
import { BACKEND } from "../helpers";
import Link from "next/link";
import AddCategory from "../components/addCategory";
import { FaThList } from "react-icons/fa";


export default function Inventory({ token, employee, categories }) {
>>>>>>> Stashed changes
  return (
    <div>
      <Head>
        <title>Vaperous M4ster - POS Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/Logo.jpg" />
        
      </Head>
      <NavBar employee={employee}></NavBar>
    
      <h1 className="text-center">Heading </h1>
      <div className="container col-lg-10 justify-content-center ">
        <div className="row">
        
        <div className="col-md-3 py-3">
        <a className="text-decoration-none text-black" href="/inventorylist">
        <div className='bg-image' style={{ maxWidth: '24rem' }}>
          <img src='/img/images.jpg' className='img-fluid' alt='Sample' />
          <div className='mask' style={{ backgroundColor: 'rgba(0, 0, 0, 0.6)' }}>
        <div className='d-flex justify-content-center align-items-center h-100'>
          <p className='text-white mb-0'>Juices</p>
        </div>
      </div>
    </div>
      </a>
    </div>


<<<<<<< Updated upstream
    <div className="col-md-3 py-3">
        <a className="text-decoration-none text-black" href="/inventorylist">
        <div className='bg-image' style={{ maxWidth: '24rem' }}>
      <img src='/img/images.jpg' className='img-fluid' alt='Sample' />
      <div className='mask' style={{ backgroundColor: 'rgba(0, 0, 0, 0.6)' }}>
        <div className='d-flex justify-content-center align-items-center h-100'>
          <p className='text-white mb-0'>Juices</p>
        </div>
      </div>
    </div>
      </a>
    </div>


    <div className="col-md-3 py-3">
        <a className="text-decoration-none text-black" href="/inventorylist">
        <div className='bg-image' style={{ maxWidth: '24rem' }}>
      <img src='/img/images.jpg' className='img-fluid' alt='Sample' />
      <div className='mask' style={{ backgroundColor: 'rgba(0, 0, 0, 0.6)' }}>
        <div className='d-flex justify-content-center align-items-center h-100'>
          <p className='text-white mb-0'>Juices</p>
        </div>
      </div>
    </div>
      </a>
    </div>


    <div className="col-md-3 py-3">
        <a className="text-decoration-none text-black" href="/inventorylist">
        <div className='bg-image' style={{ maxWidth: '24rem' }}>
      <img src='/img/images.jpg' className='img-fluid' alt='Sample' />
      <div className='mask' style={{ backgroundColor: 'rgba(0, 0, 0, 0.6)' }}>
        <div className='d-flex justify-content-center align-items-center h-100'>
          <p className='text-white mb-0'>Juices</p>
=======
      <div class="d-flex mt-3" style={{ width: "90%", alignSelf: "center" }}>
        <label
          className={styles.head}>
          PRODUCT CATEGORIES{" "}
        </label>
        <Button className="me-2 btn-sm" variant="success" onClick={submit}><FaThList className="me-2"></FaThList>Inventory Listing</Button>{' '}


        {employee.type === "ADMIN" && <AddCategory token={token} />}
      </div>
      <div className="container col-lg-10 justify-content-center mb-5">
        <div className="row">
          {categories.map((category, key) => (
            <div
              className="col-md-3 py-3 d-flex justify-content-center"
              key={key}
            >
              <Link
                className="text-decoration-none text-black"
                href={"/inventory/" + category.id}
              >
                <a className="text-decoration-none">
                  <div
                    className="bg-image shadow-lg"
                    style={{ maxWidth: "230px", height: "230px" }}
                  >
                    <img
                      src={
                        category?.image?.location
                          ? BACKEND + category.image.location
                          : "/img/blank.jpg"
                      }
                      className="img-fluid bg-transparent"
                      style={{
                        width: "230px",
                        height: "230px",
                        objectFit: "contain",
                      }}
                      alt={`${category.name}'s logo`}
                    />
                    <div
                     className={styles.mask}
                    >
                      <div className="d-flex justify-content-center align-items-center h-100">
                        <p className="text-dark mb-0">{category.name}</p>
                      </div>
                    </div>
                  </div>
                </a>
              </Link>
            </div>
          ))}
>>>>>>> Stashed changes
        </div>
      </div>
    </div>
      </a>
    </div>

    <div className="col-md-3 py-2">
        <a className="text-decoration-none text-black" href="/inventorylist">
        <div className='bg-image' style={{ maxWidth: '24rem' }}>
      <img src='/img/images.jpg' className='img-fluid' alt='Sample' />
      <div className='mask' style={{ backgroundColor: 'rgba(0, 0, 0, 0.6)' }}>
        <div className='d-flex justify-content-center align-items-center h-100'>
          <p className='text-white mb-0'>Juices</p>
        </div>
      </div>
    </div>
      </a>
    </div>

    <div className="col-md-3 py-2">
        <a className="text-decoration-none text-black" href="/inventorylist">
        <div className='bg-image' style={{ maxWidth: '24rem' }}>
      <img src='/img/images.jpg' className='img-fluid' alt='Sample' />
      <div className='mask' style={{ backgroundColor: 'rgba(0, 0, 0, 0.6)' }}>
        <div className='d-flex justify-content-center align-items-center h-100'>
          <p className='text-white mb-0'>Juices</p>
        </div>
      </div>
    </div>
      </a>
    </div>

    <div className="col-md-3 py-2">
        <a className="text-decoration-none text-black " href="/inventorylist">
        <div className='bg-image' style={{ maxWidth: '24rem' }}>
      <img src='/img/images.jpg' className='img-fluid ' alt='Sample' />
      <div className='mask ' style={{ backgroundColor: 'rgba(0, 0, 0, 0.6)' }}>
        <div className='d-flex justify-content-center align-items-center h-100'>
          <p className='text-white mb-0'>Juices</p>
        </div>
      </div>
    </div>
      </a>
    </div>

    <div className="col-md-3 py-2">
        <a className="text-decoration-none text-black" href="/inventorylist">
        <div className='bg-image' style={{ maxWidth: '24rem' }}>
      <img src='/img/images.jpg' className='img-fluid' alt='Sample' />
      <div className='mask' style={{ backgroundColor: 'rgba(0, 0, 0, 0.6)'}}>
        <div className='d-flex justify-content-center align-items-center h-100'>
          <p className='text-white mb-0'>Juices</p>
        </div>
      </div>
    </div>
      </a>
    </div>



        </div>
      </div>


    <Footer></Footer>
    </div>
  )
}
function submit(){
  document.location.href="/listing";
}
export async function getServerSideProps(context) {
  return AuthenticateEmployee(context);
}
