import Head from 'next/head'
import {Container,Row, Col, Form, FormControl, Button, InputGroup, Table, Modal} from "react-bootstrap"
import styles from '../styles/inventory.module.css'
import Image from 'next/image'
import { NavBar } from '../components/navbar'
import View from '../components/view'
import Delete from '../components/delete'
import Edit from '../components/edit'
import AddItem from '../components/addItem'
import { Footer } from '../components/footer'
import {AiOutlineSearch} from "react-icons/ai"
import {MdGridView} from "react-icons/md"
import {MdDelete} from "react-icons/md"
import {AiFillEdit} from "react-icons/ai"
import { useState } from 'react'
import { AuthenticateEmployee } from '../helpers/AuthenticateEmployee'


export default function Inventory({employee}) {
  const [show, setShow] = useState(false);
  return (
    <div>
      <Head>
        <title>Vaperous M4ster - POS Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/Logo.jpg" />
      </Head>
      <NavBar employee={employee}></NavBar>
        
  <Container className="col-lg-12 my-3 rounded-3">  
    <Row>
     <Col> 
    <Form className="d-flex col-lg-8 p-2">
    <InputGroup className="mb-3">
    <InputGroup.Text id="basic-addon1"><AiOutlineSearch></AiOutlineSearch></InputGroup.Text>
    <FormControl
      placeholder="Search"
      aria-label="Search"
      type="search"/> 
    </InputGroup>
    </Form>
    </Col>

    <Col className='p-2'>
      <div className="text-end">
    <AddItem></AddItem>
      </div>
    </Col>
  </Row>
    

  <Table striped bordered hover className="table table-image" >
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Image</th>
      <th scope="col">Product Name</th>
      <th scope="col">Variants</th>
      <th scope="col">Date Added</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td className="w-25">
      <img src="/img/images.jpg"  className="img-fluid img-thumbnail" alt="Sheep"/></td>
      <td>Flex Vape Juice</td>
      <td>Love Potion</td>
      <td>03/22/2019</td>
      <td class="py-2">
          <View></View>
         <Edit></Edit>
          <Delete></Delete>
      </td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td className="w-25">
    <img src="/img/Game-On-Juice-A3-Posters-Landscape-Nic-Salts-web.png" className="img-fluid img-thumbnail" alt="Sheep"/></td>
      <td>Flex Vape Juice</td>
      <td>Love Potion</td>
      <td>03/22/2019</td>
      <td class="py-2">
      <View></View>
         <Edit></Edit>
          <Delete></Delete>
      </td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td className="w-25">
      <img src="/img/images.jpg"  className="img-fluid img-thumbnail" alt="Sheep"/></td>
      <td>Flex Vape Juice</td>
      <td>Love Potion</td>
      <td>03/22/2019</td>
      <td class="py-2">
      <View></View>
         <Edit></Edit>
          <Delete></Delete>
      </td>
    </tr>
    <tr>
      <th scope="row">4</th>
      <td className="w-25">
    <img src="/img/Game-On-Juice-A3-Posters-Landscape-Nic-Salts-web.png" className="img-fluid img-thumbnail" alt="Sheep"/></td>
      <td>Flex Vape Juice</td>
      <td>Love Potion</td>
      <td>03/22/2019</td>
      <td class="py-2">
      <View></View>
         <Edit></Edit>
          <Delete></Delete>
      </td>
    </tr>
  </tbody>
</Table>

</Container>   

    <Footer></Footer>
    </div>
  )
}
export async function getServerSideProps(context) {
  return AuthenticateEmployee(context);
}
