import Head from 'next/head'
import {Container,Row, Col, Form, FormControl, Button, InputGroup, Table} from "react-bootstrap"
import styles from '../styles/inventory.module.css'
import { NavBar } from '../components/navbar'
import { Footer } from '../components/footer'
import {AiOutlineSearch} from "react-icons/ai"
import {MdGridView} from "react-icons/md"
import {MdDelete} from "react-icons/md"
import {AiFillEdit} from "react-icons/ai"



export default function Inventory() {
  return (
    <div>
      <Head>
        <title>Vaperous M4ster - POS Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/Logo.jpg" />
      </Head>
    <NavBar></NavBar>
        <Container className="col-lg-11 my-3 rounded-3 shadow-lg">
       
  <Row>
    <Col> 

    
    <Form className="d-flex col-lg-4 p-2">
   
    <InputGroup className="mb-3">
    <InputGroup.Text id="basic-addon1"><AiOutlineSearch></AiOutlineSearch></InputGroup.Text>
    <FormControl
      placeholder="Search"
      aria-label="Search"
      type="search"
    /> 
  </InputGroup>
 
      </Form></Col>
  </Row>
    
  <Table striped bordered hover size="sm">
  <thead>
    <tr>
      <th>Image</th>
      <th>Product ID</th>
      <th>Product Name</th>
      <th>Variants</th>
      <th>Date Added</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td  className="justify-content-center"  style={{ maxWidth: '4rem' }}><img variant="top" src="/img/93f895b604a807de99d813ec8a2e53db.jpg"  className="rounded p-1" width="130" height="120"/></td>
      <td>1029</td>
      <td>Flex Vape Juice</td>
      <td>Love Potion</td>
      <td>Date Added</td>
      <td>
      <div className="btn-group btn-group-sm" role="group" aria-label="...">
      <button type="button" className="btn btn-sm btn-secondary"><MdGridView></MdGridView></button>
    <button type="button" className="btn btn-success"><AiFillEdit></AiFillEdit></button>
    <button type="button" className="btn btn-danger"><MdDelete></MdDelete></button>
      </div>
      </td>
    </tr>
    <tr>
    <td  className="justify-content-center"  style={{ maxWidth: '4rem' }}><img variant="top" src="/img/93f895b604a807de99d813ec8a2e53db.jpg"  className="rounded p-1" width="130" height="120"/></td>
    <td>1029</td>
      <td>Flex Vape Juice</td>
      <td>Love Potion</td>
      <td>Date Added</td>
    </tr>
    <tr>
    <td  className="justify-content-center"  style={{ maxWidth: '4rem' }}><img variant="top" src="/img/93f895b604a807de99d813ec8a2e53db.jpg"  className="rounded p-1" width="130" height="120"/></td>
    <td>1029</td>
      <td>Flex Vape Juice</td>
      <td>Love Potion</td>
      <td>Date Added</td>
    </tr>

    <tr>
    <td  className="justify-content-center"  style={{ maxWidth: '4rem' }}><img variant="top" src="/img/93f895b604a807de99d813ec8a2e53db.jpg"  className="rounded p-1" width="130" height="120"/></td>
    <td>1029</td>
      <td>Flex Vape Juice</td>
      <td>Love Potion</td>
      <td>Date Added</td>
    </tr>
    <tr>
    <td  className="justify-content-center"  style={{ maxWidth: '4rem' }}><img variant="top" src="/img/93f895b604a807de99d813ec8a2e53db.jpg"  className="rounded p-1" width="130" height="120"/></td>
    <td>1029</td>
      <td>Flex Vape Juice</td>
      <td>Love Potion</td>
      <td>Date Added</td>
    </tr>
  </tbody>
</Table>

</Container>   

    <Footer></Footer>
    </div>
  )
}
