import Head from "next/head";
import { Card } from "react-bootstrap";
import styles from "../styles/inventory.module.css";
import { NavBar } from "../components/navbar";
import { Footer } from "../components/footer";
import { AuthenticateEmployee } from "../helpers/AuthenticateEmployee";
import { CategoriesQueries } from "../queries/categories";
import { BACKEND } from "../helpers";
import Link from "next/link";
import AddCategory from "../components/addCategory";

export default function Inventory({ token, employee, categories }) {
  return (
    <div className="d-flex flex-column">
      <Head>
        <title>Vaperous M4ster - POS Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/Logo.jpg" />
      </Head>
      <NavBar employee={employee}></NavBar>

      <div class="d-flex mt-3" style={{width:"90%", alignSelf:"center"}}>
        <label
          className="text-center"
          style={{
            fontSize: "2em",
            fontWeight: "bold",
            marginRight: "auto",
          }}
        >
          Product Categories{" "}
        </label>
        <AddCategory token={token} />
      </div>
      <div className="container col-lg-10 justify-content-center mb-5">
        <div className="row">
          {categories.map((category, key) => (
            <div
              className="col-md-3 py-3 d-flex justify-content-center"
              key={key}
            >
              <Link
                className="text-decoration-none text-black"
                href={"/inventory/" + category.id}
              >
                <a>
                  <div
                    className="bg-image"
                    style={{ maxWidth: "254px", height: "254px" }}
                  >
                    <img
                      src={
                        category?.image?.location
                          ? BACKEND + category.image.location
                          : "/img/blank.jpg"
                      }
                      className="img-fluid bg-dark"
                      style={{
                        width: "254px",
                        height: "254px",
                        objectFit: "contain",
                      }}
                      alt={`${category.name}'s logo`}
                    />
                    <div
                      className="mask"
                      style={{ backgroundColor: "rgba(0, 0, 0, 0.6)" }}
                    >
                      <div className="d-flex justify-content-center align-items-center h-100">
                        <p className="text-white mb-0">{category.name}</p>
                      </div>
                    </div>
                  </div>
                </a>
              </Link>
            </div>
          ))}
        </div>
      </div>

      <Footer></Footer>
    </div>
  );
}
export async function getServerSideProps(context) {
  const { props } = await AuthenticateEmployee(context);

  if (!props.employee) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }

  const categories = (await CategoriesQueries.getAll(props.token)).data
    .categories;

  return {
    props: {
      ...props,
      categories,
    },
  };
}
