import Head from 'next/head'
import Table from 'react-bootstrap/Table'
import styles from '../styles/Home.module.css'
import { NavBar } from '../components/navbar'
import { Footer } from '../components/footer'


export default function graph() {
  return (
    <div>
      <Head>
        <title>Vaperous M4ster - POS Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/Logo.jpg" />
      </Head>
    <NavBar></NavBar>
    <br></br>
    <div> 
        <h1 className="fs-2 text-center"> Sales Performance</h1>
        </div>
  
    <Footer></Footer>
    </div>
  )
}
